### ISSUE TITLE
allow text pieces to be used to open certain file types

### ISSUE THREAD

**Issue by urandom** [liferooter/textpieces#102]
Currently, text pieces does not appear in the list of applications, if I try to set it to be used to open json or xml file types. Is there a way to allow it to be used that way?

**Comment by liferooter** [comment]
Maybe I'll even add some basic text formats as supported for opening

**Comment by urandom** [comment]
Thanks. Even though it's not an editor, it's tedious to have to open downloaded files from it, rather than click them from the browser. And one of the primary use cases for me is to prettify the often-minified files from services and such, which are unreadable in a regular text editor
