### ISSUE TITLE
CTRL-C copy all buffer

### ISSUE THREAD

**Issue by mrmodolo** [liferooter/textpieces#103]
Hi!

The tool is amazing, the only problem is that if I select a single word and press CTRL-C to copy, the entire contents of the buffer are copied.

If I select a word and use the context menu with the mouse, I can copy only the selection. So it seems to me that the problem is only with CTRL-C.

The behavior is the same with flatpak installation or compiling from source.

Regards,
Marcelo Módolo

**Comment by liferooter** [comment]
I can't reproduce this bug by myself. In Text Pieces `Ctrl + Shift + C` is used to copy whole buffer. Maybe somehow your `Ctrl + C` becomes `Ctrl + Shift + C` ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by mrmodolo** [comment]
Maybe! 

With CTRL-Insert I can copy only the selection.

With Left CTRL-C and Right CTRL-C the entire buffer is copied. 

It's show me a message "Text is copied"

With CTRL-Insert no message but I can copy only the selected text.

I'm going to use CTRL-Insert since the tool is very good. I can live without CTRL-C!

Thanks,
Marcelo Módolo
