### ISSUE TITLE
Activate sponsor button

### ISSUE THREAD

**Issue by darkdragon-001** [liferooter/textpieces#108]
You need to activate your _Sponsor_ button for `FUNDING.yml` via [Settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository) :wink:

**Comment by liferooter** [comment]
I need to remove FUNDING.yml because it won't work in Russia where I live 😢
