### ISSUE TITLE
Add trim lines support (remove all new lines not just leading and trailing)

### ISSUE THREAD

**Issue by manuvarkey** [liferooter/textpieces#113]
Add support for trimming text of all new lines - not just leading and trailing. This feature will be useful in copying text from certain PDF documents where a single paragraph is split into multiple lines using newline characters.

**Comment by liferooter** [comment]
Well, now you can do it using "Remove regex" tool :)

**Comment by liferooter** [comment]
"Remove regex" -> Regex: \n -> Apply
