### ISSUE TITLE
Argument placeholder strins seems untraslated

### ISSUE THREAD

**Issue by sabriunal** [liferooter/textpieces#114]
Hi, placeholder strings of "args" seems untranslated.

![sh1](https://user-images.githubusercontent.com/6218679/199241301-e29a01ea-cec1-40d6-b5b8-190574ff2883.png)
![sh2](https://user-images.githubusercontent.com/6218679/199241303-dd8c2166-993c-481b-96ce-4f384f447b32.png)

I think it happens due to this line.

https://github.com/liferooter/textpieces/blob/main/src/widgets/Editor.vala#L204

**Comment by liferooter** [comment]
Fixed, please wait for new release
