### ISSUE TITLE
Edit Script no longer uses an external text editor

### ISSUE THREAD

**Issue by laniakea64** [liferooter/textpieces#118]
First I would like to say thank you for making Text Pieces, its scriptability makes it an awesome and handy tool!  Text Pieces custom tools have saved me quite a bit of time 👍 

I use the Text Pieces flatpak from Flathub.  In previous versions, `Preferences > Tools > (tool) > Edit Script` would open the custom tool's script in an external editor (GVim in my case).  That worked well.

The current flatpak of Text Pieces 3.4.0 changed that behavior: now it instead opens the tool script in a new Text Pieces window.  But Text Pieces [is not an editor](https://github.com/liferooter/textpieces/issues/98#issuecomment-1352707533), and its lack of the "Save" function that editors have makes Text Pieces awkward to use for editing its own custom tool scripts.  Additionally, it is not possible to interact with the Text Pieces window containing the script until the Preferences window is closed, which in combination with this behavior makes Text Pieces appear frozen even though it's not.

Although it is possible to work around this, the workaround is cumbersome:
1) Text Pieces preferences window, go back to main preferences screen
2) close Text Pieces Preferences window
3) close the Text Pieces window with the custom tool script
4) determine the script file from reading `~/.var/app/com.github.liferooter.textpieces/config/textpieces/tools.json`
5) browse to the script file manually in the system file manager
6) open the script file in text editor of choice

Could the old behavior of `Preferences > Tools > (tool) > Edit Script` please be restored?

Thanks!

**Comment by liferooter** [comment]
Lol, very unexpected behavior, but looks like I know what's the problem
