### ISSUE TITLE
Document that tools run outside of the flatpak sandbox environment

### ISSUE THREAD

**Issue by laniakea64** [liferooter/textpieces#119]
https://github.com/liferooter/textpieces/blob/b14fd2c6aeca55e8d0fd4b44997f3063bda4cc6e/src/tools/Tool.vala#L117-L123

Nice, but I wasn't aware of this until happening on that code.  It makes possible a lot of tremendously useful custom tools I wasn't writing due to the false assumption that Text Pieces ran tools inside the flatpak sandbox environment.  This also means it was unnecessary to loosen Text Pieces' flatpak sandbox permissions for the purpose of running tools that use scripts in `~/bin`, nor was it necessary to copy helper programs into `~/.local/share/textpieces`.

Given these significant power and security implications, could it please be documented somewhere outside of the code that the flatpak Text Pieces runs tools outside the flatpak sandbox, directly in the host OS environment?

**Comment by liferooter** [comment]
Fixed in Text Pieces 4.0, which will be released soon
