### ISSUE TITLE
Primary menu padding

### ISSUE THREAD

**Issue by bertob** [liferooter/textpieces#12]
The padding on the primary menu popover is too small and looks cramped. I'd bring it in line with other popovers (I think there's 12 or 18px of padding there usually).

![image](https://user-images.githubusercontent.com/1908896/131112839-ec523114-cf57-4cee-8be0-7e99125c833c.png)

Nautilus for comparison:

![image](https://user-images.githubusercontent.com/1908896/131113028-682990e8-6187-477f-b46c-6b57246711ee.png)

**Comment by bertob** [comment]
Ah, I didn't know a GTK4 port was in the works. That probably fixes this indeed.

FWIW I don't think you have to wait for libadwaita/sourceview to be stable for Flathub, you can just bundle the current snapshot :)

**Comment by liferooter** [comment]
I also wait for GTK 4.3 'cause of some textview-specific bugfixes. So I have to wait for GNOME 41

**Comment by liferooter** [comment]
Text Pieces 2.0 is on Flathub now, so I close the issue
