### ISSUE TITLE
"Select tool" button doesn't look like a button

### ISSUE THREAD

**Issue by gregorni** [liferooter/textpieces#125]
When opening the app for the first time, it's hard to tell that you have to select a tool using the button at the top. Due to its flat style, it looks more like a window title than a button.

**Comment by WeetHet** [comment]
In the modern design, nothing does... Learn to live with it. This said, I kinda like the minimalistic design

**Comment by liferooter** [comment]
> In the modern design, nothing does... Learn to live with it. That said, I kinda like the minimalistic design

Toxic :/

**Comment by liferooter** [comment]
I use the icon to make it look more like button.

**Comment by WeetHet** [comment]
> > In the modern design, nothing does... Learn to live with it. That said, I kinda like the minimalistic design
> 
> Toxic :/

It's not toxic, it's me being realistic about the current state of the application design
