### ISSUE TITLE
Asking about blueprint hack

### ISSUE THREAD

**Issue by ppvan** [liferooter/textpieces#132]
Hi, This is not a issue, i just wonder what does this hack means?
I can't reference 1 template inside another template.
But in this project you can refer the SeachBar template in Window (and many other places). Could this hack is the reason and why?

https://github.com/liferooter/textpieces/blob/b14fd2c6aeca55e8d0fd4b44997f3063bda4cc6e/resources/meson.build#L20-L29

**Comment by liferooter** [comment]
Hi. No, this hack is about broken behavior of Vala build targets in Meson. To use your custom GObject subclasses inside templates you just need to force register your custom types before loading templates, just like I do here:

https://github.com/liferooter/textpieces/blob/b14fd2c6aeca55e8d0fd4b44997f3063bda4cc6e/src/Application.vala#L233

For more information see: 
https://docs.gtk.org/gobject/func.type_ensure.html

**Comment by ppvan** [comment]
Thank you, saved my day with this technique

**Comment by ppvan** [comment]
@liferooter really sorry to inform you this, but in the process using your repo as template when build my app, i accidently did not change the developer name under appdata section, i updated it to my name, flatbot rebuild, but flathub still have your name at [https://flathub.org/vi/apps/me.ppvan.psequel](https://flathub.org/vi/apps/me.ppvan.psequel).
I really apologize for this, i will fix it as soon as possible
