### ISSUE TITLE
Separate input and output

### ISSUE THREAD

**Issue by vanillajonathan** [liferooter/textpieces#135]
Separate the input and the output into two different text views. Do not mutate the input buffer.

**Comment by liferooter** [comment]
Well, it will break the feature of sequential applying of multiple tools. Also it will make applying a tool more multi-step and less quick and convenient. By the way, I'm finishing a new version in which tools are replaced with actions which are the same thing, but they're applied immediately when choosen, so you don't need to do two steps (choosing a tool and applying it). Making Text Pieces dual-pane will require to rework everything, rethink the design and UX fundamentally, but I just don't see what is the advantages of this approach. If you tell me, I'll be thankful.

**Comment by vanillajonathan** [comment]
The benefit would be that it would be easier for me to change something in my input and transform it again. As it is now, I first have to do <kbd>Ctrl</kbd>+<kbd>Z</kbd> to undo then change my input and transform it again.

**Comment by liferooter** [comment]
I think it's pretty easy to use `Ctrl+Z`. Also I think that it's OK that it's easier to do sequential applyings than multiple undos. Anyway, both are very easy.

**Comment by vanillajonathan** [comment]
I am unsure how valuable the idea of sequential application is.

**Comment by liferooter** [comment]
Well, this feature will break two features:
- Partial application (application on selection)
  - Example: URL encoding 
- Sequential application
  - Example: data formats recoding and formatting

I think these two features are very important features of my application. It's still pretty easy to edit arguments and try different things using `Ctrl+Z`. So I don't want to change the design and implement the idea you're asking for. I understand that in some use cases it would improve the experience. But the cost is too high for me.
