### ISSUE TITLE
Tool grouping

### ISSUE THREAD

**Issue by vanillajonathan** [liferooter/textpieces#137]
Maybe tools could be grouped into different categories.

Categories could be checksum, hash, encoding/decoding, and transforms (uppercase, lowercase, title case, reverse, etc).

**Comment by liferooter** [comment]
Text Pieces uses search for choosing tools, so there's no need for grouping

**Comment by vanillajonathan** [comment]
But when you have many tools, it might be difficult to know what tools exists so maybe there could be some tags, categories or grouping. So you can search for "hash" or click on "hash" to find all hash function tools.

**Comment by liferooter** [comment]
Well, maybe a better idea is to have some kind of tags or keywords which would be respected by the search algorithm

**Comment by liferooter** [comment]
> Well, maybe a better idea is to have some kind of tags or keywords which would be respected by the search algorithm 🤔

I've thought about it and decided that this feature is not needed because all keywords are mostly included in the name or the description of the tool.
