### ISSUE TITLE
Respect my theme variant

### ISSUE THREAD

**Issue by lobau** [liferooter/textpieces#14]
I use default adwaita (in light mode) and the current interface is pretty jarring for people with poor vision like me.
The app should just follow my system theme instead of enforcing a dark theme, or at least offer a setting.
 @bertob

**Comment by bertob** [comment]
The current Adwaita dark is primarily intended for media apps, I don't see a reason to use it here.

Once the system-wide dark preferences lands (probably next cycle) the app should just follow that.

**Comment by liferooter** [comment]
GNOME will support global color scheme settings since 42, Elementary already support it (I don't know whether Elementary supports all three 'prefer-dark', 'prefer-light' and 'default' options btw). I think it will be good idea to show option if system doesn't support color schemes and just respect system color scheme with dark as default if it supports. 
@bertob

**Comment by lobau** [comment]
Why dark as default, tho? Sorry to be insistent, but you even have a "Please don't theme" badge, and yet you don't respect my theme and enforce dark theme. It has significant usability issues for myopic people like me. Even the terminal can be switched to light mode :-)

**Comment by liferooter** [comment]
If your system don't have color scheme support, you can choose theme in the app. If you have it and dark mode is kind of problem for you, so you can just switch to "Prefer light" mode. Text Pieces will follow your setting.

**Comment by lobau** [comment]
I don't see the setting in the app. I'm on 2.3.1 straight from Fedora Software.
I'll pull from main directly and see if that's better. Thanks :)

**Comment by liferooter** [comment]
Wait, this option was added in 2.3.1

**Comment by liferooter** [comment]
It should be in primary menu

**Comment by lobau** [comment]
This is what I see
![image](https://user-images.githubusercontent.com/6750584/135498477-35df182a-07da-4906-a2a2-da6c86c2a4bd.png)

![image](https://user-images.githubusercontent.com/6750584/135498550-65d66b46-fad3-4f70-ac85-9ec6b0aba84e.png)

![image](https://user-images.githubusercontent.com/6750584/135498624-52c1c296-6782-42d4-946f-9ad433c2520c.png)

**Comment by liferooter** [comment]
This really don't work. I'm sorry. I'll reopen the issue and fix the bug :)

**Comment by lobau** [comment]
Thanks a lot :-)

**Comment by liferooter** [comment]
I hope this commit doesn't turn out to be broken :)

**Comment by lobau** [comment]
Yes I just tested and it works now. Thanks a lot!
