### ISSUE TITLE
Upgrade from GNOME 44 runtime

### ISSUE THREAD

**Issue by bragefuglseth** [liferooter/textpieces#146]
Hey, Brage from the GNOME Circle Committee here!

Just wanted to reach out and say that Text Pieces is currently on the GNOME 44 runtime, which is outdated. Check out https://gitlab.gnome.org/Teams/Circle/-/issues/223 for more info.

From reading through #141, it seems like the app is currently in a fluctuating state. It can stay for now if it upgrades its runtime, but if you're unsure if it can be kept up to Circle's standards going forward, please contact us so we can discuss exiting the app from Circle for now. It could always rejoin later if you'd like it to :slightly_smiling_face:

**Comment by liferooter** [comment]
Fixed in Text Pieces 4.0, which will be released soon, before 30th of April :)
