### ISSUE TITLE
Dark theme setting should be shown when system color sheme is 'default'

### ISSUE THREAD

**Issue by liferooter** [liferooter/textpieces#23]
Dark theme setting should be shown when user's system doesn't have color sheme support or color sheme is 'default', not 'prefer-dark' or 'prefer-light'. Currently dark theme setting is shown only on systems which don't support color schemes.

**Comment by MoonlightGhost** [comment]
I think it is not that necessary while Adwaita is not released yet

**Comment by liferooter** [comment]
This behavior is not recommended by GNOME Dark Style Preference Initiative (https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference), so I am closing this issue
