### ISSUE TITLE
macOS Version

### ISSUE THREAD

**Issue by WeetHet** [liferooter/textpieces#60]
You should definitely create macOS version

**Comment by liferooter** [comment]
Contributions are welcome :)

**Comment by WeetHet** [comment]
I don't know gtk and vala

**Comment by WeetHet** [comment]
Also, there is a bug with gtk shadows on macOS, so you should try to patch it

**Comment by liferooter** [comment]
I have no MacBook and macOS to test so I can't test such build. You should wait until anyone will help me with such build.

**Comment by WeetHet** [comment]
I will help you then

**Comment by liferooter** [comment]
> Also, there is a bug with gtk shadows on macOS, so you should try to patch it

Yeah, I know that there are a lot of issues with GTK on macOS, but I advice you to report them to GTK developers, not to me

**Comment by WeetHet** [comment]
> > Also, there is a bug with gtk shadows on macOS, so you should try to patch it
> 
> Yeah, I know that there are a lot of issues with GTK on macOS, but I advice you to report them to GTK developers, not to me

I'm a noname for GTK developers

**Comment by liferooter** [comment]
> > > Also, there is a bug with gtk shadows on macOS, so you should try to patch it
> > 
> > 
> > Yeah, I know that there are a lot of issues with GTK on macOS, but I advice you to report them to GTK developers, not to me
> 
> I'm a noname for GTK developers

You are not noname, you are user. In open-source world your bug report and my bug report are equal. Also I can't properly report bug I can't reproduce.
