### ISSUE TITLE
Translation of tools.pot

### ISSUE THREAD

**Issue by Vistaus** [liferooter/textpieces#72]
Quick question: where should I place the translation of tools.pot? Normally, po files should be in the po directory, but in this case, the po files in there are already used for the application translation. So where should I put the translation of the tools.pot file?

**Comment by liferooter** [comment]
Translation of tools.pot should be placed in main .po file right after translation of textpieces.pot

**Comment by Vistaus** [comment]
I understand. But what file name I should give it? nl.po is already in use by the translation of textpieces.pot, so what name should I give the translation file of tools.pot?

**Comment by liferooter** [comment]
Just insert it in the end of nl.po
