### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by WeetHet** [liferooter/textpieces#77]
Consider rewriting this undeniably perfect application in a new, modern and safe language named Rust. For more information about rust visit
https://www.rust-lang.org

**Comment by liferooter** [comment]
I'll do it right after you'll create good GIR bindings for Haskell and make Haskell good programming language :)

**Comment by liferooter** [comment]
In progress.

**Comment by liferooter** [comment]
Fixed in Text Pieces 4.0, which will be released soon
