### ISSUE TITLE
Build error on Debian

### ISSUE THREAD

**Issue by CountOmega** [liferooter/textpieces#82]
I am trying a local build . I have all the relevant dependencies installed. 
OS: debian testing GCC: 11
I attached the test log below
[meson_log.txt](https://github.com/liferooter/textpieces/files/8723165/meson_log.txt)
.

**Comment by liferooter** [comment]
There was an issue with `gtksourceview` namespace naming. Now it's fixed. Try to build new version of Text Pieces.

**Comment by CountOmega** [comment]
latest version builds, thanks
