### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by gargullia** [liferooter/textpieces#83]
The app window is not showing for me on either Wayland or Xorg. I get nothing in the logs. If I start it from CLI no errors show up. The process keeps running. System Monitor shows it as sleeping. The flatpak version works fine, but it's not worth the overhead since I don't use any flatpak apps at all. 

Tested on archlinux and Fedora 36

**Comment by liferooter** [comment]
I've just checked and now can confirm that this bug really exists for native builds. I have some ideas why does it happen. Trying to fix it.
Thank you for your report!

**Comment by liferooter** [comment]
Fixed by commit 21108a1599d8605ebbdee5ec0814eca1a2c6f5b5
