### ISSUE TITLE
Feature: Undo/Redo buttons

### ISSUE THREAD

**Issue by mifot** [liferooter/textpieces#95]
It would be nice to have "undo" button e.g. next to "Apply". It could simplify work a lot! Now once I apply some tool to my text and want to use the second tool I have to reopen the original text. Also, some two section window (one for input, one for output) might be a solution or the next interesting feature.

**Comment by liferooter** [comment]
Text Pieces supports common hotkeys for Undo/Redo. You can use `Ctrl+Z` for undo and `Ctrl+Shift+Z`/`Ctrl+Y` for redo. It works with both manual editing and tool applying.

**Comment by liferooter** [comment]
However, I'll add undo and redo buttons for better accessability. Thank you for your report!

**Comment by mifot** [comment]
yes, I noticed hotkeys. Thanks in advance for a new buttons.

**Comment by sonnyp** [comment]
No GNOME app has undo/redo buttons – not even Text Editor.
Undo/redo is already documented in the shortcut window.

> once I apply some tool to my text and want to use the second tool I have to reopen the original text.

I've had this problem as well. I agree it warrants a UI solution.

I think the input/output panels is a good idea and would fit nicely with https://github.com/liferooter/textpieces/issues/70 . It may be difficult to integrate with current flow, perhaps as a separate mode.

Another one would be to keep and expose a history of transformation – maybe in a sidebar. 

Something like

```
---
0. Original
---
1. JSON to YAML
---
2. Base 64 Encode
---
```

**Comment by VBBr** [comment]
> No GNOME app has undo/redo buttons

gnome-builder has undo/redo in right-click menu

**Comment by liferooter** [comment]
No undo/redo button are planned. You can use hotkeys or context menu
