### ISSUE TITLE
Feature: In-place editing

### ISSUE THREAD

**Issue by williamd1k0** [liferooter/textpieces#98]
So far Text Pieces only supports in-memory editing, even when you load text from a file.

In other words:
- Make the "Save to File" button write directly to the same file (if the text was loaded from a file);
- And add a "Save (copy) as..." button to save to a different file.

**Comment by liferooter** [comment]
Honestly I don't want to make Text Pieces an editor. Also good file dialogs (like in GNOME) will suggest you the folder you opened a file from on save

**Comment by liferooter** [comment]
Also some of tools converts content from one type to another, so to save content back to the file by default would be weird
